#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: 2rs2ns.com

# Short bio or description (displayed in the header)
description: C.J. Herrmann, Web Developer in Eastern North Carolina

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://en.gravatar.com/userimage/41685361/49e8889171ab3d7aa19002ff0f026e10.jpeg

# Includes an icon in the footer for each username you enter
footer-links:
  github: https://github.com/Siege36

# Enable google analytics
google_analytics: true

# Used for Sitemap.xml and your RSS feed
url: http://2rs2ns.com

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: "http://2rs2ns.com"

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
